# Generated by Django 4.2 on 2023-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
